In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import numpy as np

zero_D_arr = np.array(123)
print(zero_D_arr)
print(f'Dimension: {zero_D_arr.ndim}')

123
Dimension: 0


In [15]:
one_D_arr = np.array([1, 2, 3, 4, 5])
print(one_D_arr)
print(f'Dimension: {one_D_arr.ndim}')

[1 2 3 4 5]
Dimension: 1


In [16]:
two_D_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(two_D_arr)
print(f'Dimension: {two_D_arr.ndim}')

[[1 2 3]
 [4 5 6]]
Dimension: 2


In [19]:
three_D_arr = np.array(
        [
            [
                [1, 2, 3], 
                [4, 5, 6],
                [11, 22, 33]
            ],
            [
                [7, 8, 9],
                [10, 11, 12],
                [44, 55, 66]
            ]
        ]
    )
print(three_D_arr)
print(f'Dimension: {three_D_arr.ndim}')

[[[ 1  2  3]
  [ 4  5  6]
  [11 22 33]]

 [[ 7  8  9]
  [10 11 12]
  [44 55 66]]]
Dimension: 3


In [23]:
file = np.array([1, 2, 3, 4, 5])

np.save('np_save', file)

In [24]:
buffer = np.load('./np_save.npy')
print(buffer)

[1 2 3 4 5]


In [26]:
temp_arr = np.array([1, 2, 3, 4, 5])
np.savetxt("Numpy_arr", temp_arr)

arr_buffer = np.loadtxt('./Numpy_arr')
print(arr_buffer)

[1. 2. 3. 4. 5.]


## Indexing

In [27]:
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [ ]:
# For [1 3 5 7 9] array, this indexed array will print elements specified in list
"""
    4: Element at index 4 = 9
    0: Element at index 0 = 1
    2: Element at index 2 = 5
    -1: Element at index -1 = 9
    -2: Element at index -2 = 7
    
    Therefor the output is: [9 1 5 9 7]
"""

arr_index = arr[np.array([4, 0, 2, -1, -2])]
print(arr_index)

[9 1 5 9 7]


## Indexing 1D array

In [50]:
arr_1 = np.arange(12)

print(arr_1)
print(arr_1[0])
print(arr_1[1])
print(arr_1[5])


[ 0  1  2  3  4  5  6  7  8  9 10 11]
0
1
5


## Indexing 2D array

In [54]:
arr_1 = arr_1.reshape(3, 4)
print(arr_1)
print(f'arr_1[0, 3]: {arr_1[0, 3]}')
print(f'arr_1[1, 2]: {arr_1[1, 2]}')
print(f'arr_1[2, 1]: {arr_1[2, 1]}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr_1[0, 3]: 3
arr_1[1, 2]: 6
arr_1[2, 1]: 9


In [ ]:
arr_1 = np.array([[[1, 2, 3], [4, 5, 6],[11, 22, 33]],[[7, 8, 9],[10, 11, 12],[44, 55, 66]]])

print(arr_1)

print(f'Element at arr_1[0, 1, 2]: {arr_1[0, 1, 2]}')
print(f'Element at arr_1[0, 1, 2]: {arr_1[0, 0, 1]}')
print(f'Element at arr_1[0, 1, 2]: {arr_1[1, 1, 2]}')
print(f'Element at arr_1[0, 1, 2]: {arr_1[0, 1, 1]}')

[[[ 1  2  3]
  [ 4  5  6]
  [11 22 33]]

 [[ 7  8  9]
  [10 11 12]
  [44 55 66]]]
Element at arr_1[0, 1, 2]: 6
Element at arr_1[0, 1, 2]: 2
Element at arr_1[0, 1, 2]: 12
Element at arr_1[0, 1, 2]: 5


## Slicing 1D array

In [74]:
arr = np.arange(6)
print(arr[0:3])

[0 1 2]


## Slicing 2D array

In [113]:
arr = np.arange(12)
arr = arr.reshape(3, 4)
print(arr)
print(arr[0:, 1:2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1]
 [5]
 [9]]


## Broadcasting

In [115]:
arr_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr_2 = np.array([9, 10, 11, 12])

print(f'{arr_1}\n')
print(f'{arr_2}\n')
print(f'{arr_1 + arr_2}\n')

[[1 2 3 4]
 [5 6 7 8]]

[ 9 10 11 12]

[[10 12 14 16]
 [14 16 18 20]]



## Statistical Functions

In [ ]:

# all ele sum / total ele
print(np.mean([1, 2, 3, 4, 5, 6]))

# Middle ele
print(np.median([1, 2, 3, 4, 5]))

# average
print(np.average([1, 2, 3, 4, 5, 6]))

# Variance
print(np.var([1, 2, 3, 4, 5]))

# Percentile
print('\n')
print(np.percentile([90, 43, 54], 0))
print(np.percentile([90, 43, 54], 25))
print(np.percentile([90, 43, 54], 50))
print(np.percentile([90, 43, 54], 75))
print(np.percentile([90, 43, 54], 100))

# Range
print('\n')
print(np.ptp([1, 2, 3, 4]))



3.5
3.0
3.5
2.0


43.0
48.5
54.0
72.0
90.0


3
